sudo: true
dist: trusty
language: python
python:
  - "2.6"
  - "2.7"
  - "3.4"
  - "3.5"

install:
  - "pip install -r requirements.txt"

script:
  - echo -e "holds(test,t1)" | python high_level_parsing.py
  - echo -e "Agent james" | python prototypes.py
  - python cleaning.py
  - echo -e "implies(kind(james),help(james))\nimplies(kind(james),help(james))" | python dcec_container.py